### ISSUE TITLE
[Question] What are Seed Lists/Leech Lists and their limits?

### ISSUE THREAD

**Issue by 9Oc** [Roardom/UNIT3D-Announce#13]
I have some users that seem to be hitting a type of limit for downloading/seeding but I'm not sure what the limits mean or how they are reached.

![HBFOahb 1](https://github.com/user-attachments/assets/d0a4e736-3574-47ee-ac59-36eeacfc861b)
Seen here this user seems to have hit some limit where they cannot download anything even though their total download slot limit in their user profile hasn't been reached.

I tried looking through the UNIT3D code to see if their was documentation on this but couldn't find any comments about what these lists and their respective max numbers mean. If someone could explain to me what these are and how to change them so people don't get blocked from downloading/seeding it would be much appreciated.

**Comment by Roardom** [comment]
This is clearly defined in the config: https://github.com/Roardom/UNIT3D-Announce/blob/6367f8c082a4af2e4142bf2e1f1db94edc336289/.env.example#L121-L148

**Comment by 9Oc** [comment]
Thank you sir, appreciate your time.

Is it normal for people to get rate limited very quickly with these default settings for the list rate limits? I have couple people who did at one time (weeks ago) add 100-200 torrents to their clients at once and they got list rate limited but now seem to continue to be limited far more than they used to be e.g. only able to add 5-10 torrents to their client every 30 minutes or so. And if they do go over 10 they cannot download anything more for hours/days.

If I understand right in this string of numbers: "60=10;900=25;7200=125;86400=500;604800=2500" it is saying that for instance every 60 seconds you cannot add more than 10 torrents, or every 900 seconds more than 25 etc. Is that correct?

**Comment by Roardom** [comment]
I must note this project is not released yet and is not intended for usage by the general public, nor does it have a foss license to do so.

> Is it normal for people to get rate limited very quickly with these default settings for the list rate limits?

These settings work for me.

> Is that correct?

Yes
